import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Physical AI & Humanoid Robotics Book Sidebar Configuration
 *
 * Uses auto-generated sidebar from folder structure.
 * Each module folder contains a _category_.json for customization.
 */
const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from docs folder structure
  bookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
